### PR TITLE
Removed dependency on ring-core. Fixes #19

### LINKED ISSUE #19: Remove dependency on ring-core
`ring-cors` depends on `ring-core` for the sole method [get-header](https://github.com/ring-clojure/ring/blob/ecf06c142ee4195756f94b780c238f3a917b3b8d/ring-core/src/ring/util/response.clj#L183).

It would be nice to drop this dependency and simply copy the code in `ring-cors` for 2 reasons:

* it reduces potential for versions conflict on `ring-core`
* `ring-core` ships with lots of irrelevant transitive dependencies

What do you think? I can create a PR if needed.

### PR DESCRIPTION
**Pull request by jeluard**

### CODE REVIEW

**Comment by r0man** [comment]
@jeluard Could you fix the lint error, then I think this is ready to be merged!

**Comment by jeluard** [comment]
Done!

**Comment by r0man** [comment]
@jeluard Thanks! Released as `0.1.11`.

**Comment by jeluard** [comment]
Great thanks!

**Pull request merged**
