### PR TITLE
Adding CORS header concerns

### PR DESCRIPTION
**Pull request by enriclluelles**
Hi there,

Thanks for this library. I added the handling of header whitelisting to it. 

And at the same time tried to make some parts of the code it a little bit more readable. 
I'm a ruby guy who's only started doing clojure recently so even though I tried to be idiomatic I may haven't been.

Cheers

### CODE REVIEW

**Comment by frankiesardo** [comment]
We're currently stuck because we cannot set  :access-control-allow-credentials "true".

Is there a quick workaround we can implement while this gets fixed?

**Comment by r0man** [comment]
@frankiesardo I think the regression introduced in this PR has already been fixed. I just added a test case for `:access-control-allow-credentials` over here https://github.com/r0man/ring-cors/commit/7418fe9764de32fb31437fa0b8f02f5b72c98d05 . What exactly is the problem? 
Patch with tests welcome!

**Comment by frankiesardo** [comment]
Yup it works! The error was caused by our mistake and by searching this library it seemed that this option was not supported. We've been too quick to blame others :smile: Thanks for adding the test case anyway, it makes it easier to see which keywords we can pass to `wrap-cors`.

**Comment by r0man** [comment]
Ok, cool. :)

**Pull request merged**
